# -*- coding: utf-8 -*-
"""Practice_exm_chance_Python_09_IMPORTANT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6KJ9-9f6IAgEgjTZfFapYKkIKOwozlm
"""

def ANGELOO():
  print("Valorant proooo")

ANGELOO()

def Ridha():
  print("Your roll number is ",10)

Ridha()

a=input("Enter your name: ")
b=int(input("Enter your roll number: "))
c=input("Enter your Mail Id: ")
d=input("Enter your place: ")
def Ridha(a,b,c,d):
  print("My name is ",a)
  print("Roll number: ",b)
  print("Mail Id:",c)
  print("Location:",d)
Ridha(a,b,c,d)

d=[]
a=input("Enter your Name: ")
def firstname(a):
  print(a[0:6])
def middlename(a):
  print(a[7:11])
def surname(a):
  print(a[12:16])
firstname(a)
middlename(a)
surname(a)

def name():
  y=x.split()
  print("My First name is",y[0])
  print("My Middle name is",y[1])
  print("My Surname is",y[2])
x=input("Enter your name: ")
name()

d=[]
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
def swap(a,b):
  print(b,a)

swap(a,b)

