# -*- coding: utf-8 -*-
"""practice_exm_chance_python_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c93wTyn4EDmIhccmFDKYxTZelvQjU96h
"""

x=[52,85,95,75,85,754,24,547,654,858]
def num(x):
  print("Sum: ",sum(x))

num(x)

def oddeven(x):
  x=[2,5,6,3,4,1,7,8,85,54]
  odd=[]
  even=[]
  for i in x:
    if (i%2==0):
      even.append(i)
    else:
      odd.append(i)
  print("Odd List = ",sum(odd))
  print("Even List = ",sum(even))

oddeven(x)

x="Python is a high-level, general-purpose programming language."
y=''
vowels=['a','e','i','o','u']
for i in range(len(x)):
    if x[i] not in vowels:
      y=y+x[i] 
print(y)

